//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCompanyCall.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmployee
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Image { get; set; }
        public Nullable<int> Department { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual TblDepartments TblDepartments { get; set; }
    }
}
